spring:
  jms:
    servicebus:
      connection-string: *
      idle-timeout: 1800000
      topic-client-id: riverobservationstopic

station:
  id: LEVK1
  seed-water-level: 25
  seed-water-flow: 100
  increment-value: 0.3
  lat: 39.326944
  lon: -94.909444
server:
  port: 8888
