

spring:
  jms:
    servicebus:
      connection-string: "Endpoint=sb://rivers.servicebus.windows.net/;SharedAccessKeyName=ReadWrite;SharedAccessKey=B0B1lAicVuOaq2SCC4+EE2xYwonYn8Wl80eIycG0jfY="
      idle-timeout: 1800000

station:
  id: LEVK1;
  seed-water-level: 25
  seed-water-flow: 100
  increment-value: 0.3
  lat: 39.326944
  lon: -94.909444
server:
  port: 8888
