server:
  port: 9999

spring:
  cloud:
    azure:
      credential-file-path: river.azureauth
      resource-group: azure-training
      region: Central US
      storage.account: rivermonitorstorage
      use-http: true
  data:
    rest:
      basePath: /api/v1
  datasource:
    url: jdbc:sqlserver://*
    username: NotificationService
    password: *
  jms:
    servicebus:
      connection-string: Endpoint=sb://*
      idle-timeout: 1800000
      topic-client-id: floodadvisorytopic
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
seed-email-count: 500
