spring:
  datasource:
    url: jdbc:sqlserver://*
    username: FloodWarningService
    password: AYcsiy40R8a3uIP7let/mw==
  jms:
    servicebus:
      connection-string: Endpoint=sb://*
      topic-client-id: riverobservationstopic
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
