spring:
  cloud:
    azure:
      credential-file-path: river.azureauth
      resource-group: azure-training
      region: Central US
      storage.account: rivermonitorstorage
      use-http: true
  datasource:
    url: jdbc:sqlserver://*
    username: FloodWarningService
    password: *
  jms:
    servicebus:
      connection-string: *
      idle-timeout: 1800000
      topic-client-id: riverobservationstopic
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
