server:
  port: 8001
spring:
  data:
    rest:
      basePath: /api/v1
  datasource:
    url: jdbc:sqlserver://*
    username: FloodWarningService
    password: *
  jms:
    servicebus:
      connection-string: Endpoint=sb://*
      idle-timeout: 1800000
      topic-client-id: riverobservationstopic
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
