azure:
  storage:
    connection-string: ***

spring:
  jms:
    servicebus:
      connection-string: ***
      idle-timeout: 1800000
      topic-client-id: riverobservationstopic
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true
    show-sql: true

  datasource:
    url: ***
    username: FloodWarningService
    password: AYcsiy40R8a3uIP7let/mw==

